type ButtonKeys =
  | "BUTTON_BOTTOM"
  | "BUTTON_RIGHT"
  | "BUTTON_LEFT"
  | "BUTTON_TOP"
  | "BUMPER_LEFT"
  | "BUMPER_RIGHT"
  | "TRIGGER_LEFT"
  | "TRIGGER_RIGHT"
  | "BUTTON_CONTROL_LEFT"
  | "BUTTON_CONTROL_RIGHT"
  | "BUTTON_JOYSTICK_LEFT"
  | "BUTTON_JOYSTICK_RIGHT"
  | "D_PAD_UP"
  | "D_PAD_BOTTOM"
  | "D_PAD_LEFT"
  | "D_PAD_RIGHT"
  | "BUTTON_CONTROL_MIDDLE";

type AxesKeys =
  | "JOYSTICK_LEFT_HORIZONTAL"
  | "JOYSTICK_LEFT_VERTICAL"
  | "JOYSTICK_RIGHT_HORIZONTAL"
  | "JOYSTICK_RIGHT_VERTICAL";
